# Generated by Django 4.2.3 on 2023-08-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='author_pseudonym',
            field=models.CharField(default='', max_length=30),
        ),
    ]
